---
- hosts: pi
  tasks:
    - name: download docker
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: a+x
      become: true
    - name: install docker
      shell: creates=/usr/bin/docker /tmp/get-docker.sh
      become: true
    - name: add pi to docker group
      user: name=pi group=docker append=yes
      become: true
    - name: install python-pip
      apt: name={{ item }} state=present
      with_items:
        - python-pip
      become: true
    - name: install docker-compose
      pip:
        name: docker-compose
      become: true
