---
- hosts: pi
  tasks:
    # Update apt packages
    - name: Update apt packages
      become: yes
      apt:
        update_cache=yes

    # Upgrade apt packages
    - name: Upgrade apt packages
      become: yes
      apt:
        upgrade=dist